language: r
r:
  - oldrel
  - release
#  - devel
cache: packages

# add tcltk support on Ubuntu
addons:
  apt:
    packages:
    - tcl8.6
    - tk8.6

# for the tcltk package, we need some special treatment (as the Travis environment has no display)
# see https://stackoverflow.com/a/55674747
services:
  - xvfb
before_install:
 - export DISPLAY=:99.0

warnings_are_errors: false

after_success:
  - Rscript -e 'covr::codecov()'

# see https://docs.travis-ci.com/user/languages/r/